[build-system]
requires = ["setuptools>=61", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "tb_hide"
version = "0.1.0"
description = "A Python package for traceback frame hiding"
readme = "README.md"
requires-python = ">=3.10"
license = { text = "MIT" }
authors = [
    {name = "YXProtocol", email = "YXProtocol@outlook.com"}
]
keywords = [
    "python",
    "traceback",
    "exception",
    "error-handling",
    "decorator",
    "debugging",
    "traceback-frame",
    "traceback-filter",
    "hide-traceback",
    "developer-tools",
    "tb-hide",
]
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]
dependencies = []

[tool.setuptools.packages.find]
where = ["src"]